export const SOME_ACTION = 'SOME_ACTION'
export const UPDATE_COUNTER_CHANGE_FIELD = 'UPDATE_COUNTER_CHANGE_FIELD'
export const UPDATE_COUNTER = 'UPDATE_COUNTER'
export const UPDATE_COUNTER_REJECTED = "UPDATE_COUNTER_REJECTED"
export const UPDATE_COUNTER_FULFILLED = "UPDATE_COUNTER_FULFILLED"
export const GENERIC_ERROR = 'GENERIC_ERROR'
